language: c

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - git clone https://github.com/smealum/ctrulib.git
  - git clone --recursive https://github.com/Steveice10/bannertool.git
  - git clone https://github.com/profi200/Project_CTR.git

install:
  - sudo perl devkitARMupdate.pl
  - cd ctrulib/libctru 
  - make
  - cd ..
  - sudo cp -rf libctru/ ${DEVKITPRO}
  - cd ..
  - cd bannertool
  - make 
  - sudo cp -rf output/linux-x86_64/bannertool ${DEVKITARM}/bin/
  - cd ..
  - cd Project_CTR/makerom
  - make
  - sudo cp -rf makerom ${DEVKITARM}/bin/
  
script:
  - make